import {
  type IDataObject,
  type IHookFunctions,
  type INodeType,
  type INodeTypeDescription,
  type IWebhookFunctions,
  type IWebhookResponseData,
} from 'n8n-workflow';

import { ticketZeroApiRequest } from '../TicketZero/GenericFunctions';
import { verifyTicketZeroSignature } from './verify';

/**
 * TicketZero trigger.
 *
 * When the workflow is activated the node automatically creates a webhook
 * subscription in TicketZero (`POST /v1/api-public/webhooks`) pointing at the
 * webhook URL generated by n8n; when it is deactivated the subscription is
 * deleted again. The secret returned once is stored in the workflow static data
 * and is used to HMAC-verify every incoming event (`X-SG-Signature:
 * sha256=<hex>` over `"<X-SG-Timestamp>.<rawBody>"`, ±5 min replay window).
 */
export class TicketZeroTrigger implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'TicketZero Trigger',
    name: 'ticketZeroTrigger',
    icon: 'file:ticketzero.svg',
    group: ['trigger'],
    version: 1,
    subtitle: '={{$parameter["events"].join(", ")}}',
    description: 'Starts a workflow on TicketZero events',
    defaults: { name: 'TicketZero Trigger' },
    usableAsTool: true,
    inputs: [],
    outputs: ['main'],
    credentials: [{ name: 'ticketZeroApi', required: true }],
    webhooks: [
      {
        name: 'default',
        httpMethod: 'POST',
        responseMode: 'onReceived',
        path: 'webhook',
      },
    ],
    properties: [
      {
        displayName: 'Events',
        name: 'events',
        type: 'multiOptions',
        required: true,
        default: [],
        description: 'Which TicketZero events to listen for',
        options: [
          {
            name: 'Contact Created',
            value: 'contact.created',
            description: 'A new contact was created',
          },
          {
            name: 'Conversation Assigned',
            value: 'conversation.assigned',
            description: 'A conversation was assigned to a team member',
          },
          {
            name: 'Conversation Created',
            value: 'conversation.created',
            description: 'A new conversation was created',
          },
          {
            name: 'Message Received',
            value: 'message.received',
            description: 'An inbound customer message arrived',
          },
          {
            name: 'Message Sent',
            value: 'message.sent',
            description: 'An outbound message was sent',
          },
          {
            name: 'Status Changed',
            value: 'conversation.status_changed',
            description: 'The status of a conversation changed',
          },
        ],
      },
    ],
  };

  webhookMethods = {
    default: {
      async checkExists(this: IHookFunctions): Promise<boolean> {
        const webhookData = this.getWorkflowStaticData('node');
        if (!webhookData.subscriptionId) return false;
        try {
          await ticketZeroApiRequest.call(
            this,
            'GET',
            `/v1/api-public/webhooks/${webhookData.subscriptionId}`,
          );
          return true;
        } catch {
          // Subscription no longer exists (e.g. deleted in TicketZero) -> drop
          // the static data so create() provisions a new one.
          delete webhookData.subscriptionId;
          delete webhookData.secret;
          return false;
        }
      },

      async create(this: IHookFunctions): Promise<boolean> {
        const webhookUrl = this.getNodeWebhookUrl('default');
        if (!webhookUrl) return false;
        const events = this.getNodeParameter('events', []) as string[];
        const workflowName = this.getWorkflow().name ?? 'Workflow';
        const body: IDataObject = {
          name: `n8n: ${workflowName}`.slice(0, 120),
          url: webhookUrl,
          events: events.length > 0 ? events : ['*'],
        };
        const response = await ticketZeroApiRequest.call(
          this,
          'POST',
          '/v1/api-public/webhooks',
          body,
        );
        if (!response?.id || !response?.secret) return false;
        const webhookData = this.getWorkflowStaticData('node');
        webhookData.subscriptionId = response.id as string;
        webhookData.secret = response.secret as string;
        return true;
      },

      async delete(this: IHookFunctions): Promise<boolean> {
        const webhookData = this.getWorkflowStaticData('node');
        if (webhookData.subscriptionId) {
          try {
            await ticketZeroApiRequest.call(
              this,
              'DELETE',
              `/v1/api-public/webhooks/${webhookData.subscriptionId}`,
            );
          } catch {
            // Best-effort: already deleted is fine.
          }
          delete webhookData.subscriptionId;
          delete webhookData.secret;
        }
        return true;
      },
    },
  };

  async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
    const headers = this.getHeaderData() as IDataObject;
    const bodyData = this.getBodyData() as IDataObject;
    const webhookData = this.getWorkflowStaticData('node');
    const secret = webhookData.secret as string | undefined;

    if (secret) {
      // Verify the signature over the RAW bytes - re-serializing would change
      // the exact byte sequence (key order/whitespace) and break the HMAC.
      const req = this.getRequestObject() as unknown as { rawBody?: Buffer | string };
      const rawBody = req.rawBody;
      if (rawBody === undefined) {
        return reject.call(this, 'raw_body_unavailable');
      }
      const rawString = Buffer.isBuffer(rawBody) ? rawBody.toString('utf8') : String(rawBody);
      const result = verifyTicketZeroSignature({
        secret,
        signatureHeader: String(headers['x-sg-signature'] ?? ''),
        timestamp: String(headers['x-sg-timestamp'] ?? ''),
        rawBody: rawString,
        nowSeconds: Math.floor(Date.now() / 1000),
      });
      if (!result.ok) {
        return reject.call(this, result.reason);
      }
    }

    return {
      workflowData: [this.helpers.returnJsonArray([bodyData])],
    };
  }
}

/** Responds with 401 and suppresses the default 200 webhook response. */
function reject(this: IWebhookFunctions, reason: string): IWebhookResponseData {
  const res = this.getResponseObject();
  res.status(401).json({ error: reason });
  return { noWebhookResponse: true };
}
